# Generated by Django 5.2.1 on 2025-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=100)),
                ('rel_date', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('hero', models.CharField(max_length=100)),
                ('heroine', models.CharField(max_length=100)),
                ('imdb_rating', models.FloatField()),
                ('hit_flop', models.BooleanField(default=True, null=True)),
                ('runtime', models.IntegerField(help_text='Enter runtime in minutes')),
            ],
        ),
    ]
