# Generated by Django 5.2.1 on 2025-06-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobilenumber',
            field=models.IntegerField(null=True),
        ),
    ]
