# Generated by Django 5.2.1 on 2025-05-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='rel_date',
            new_name='rel_year',
        ),
    ]
