# Generated by Django 5.2.1 on 2025-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_alter_user_age_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobilenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
