# Generated by Django 5.2.1 on 2025-06-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_rename_rel_date_movies_rel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='hit_flop',
        ),
    ]
