# Generated by Django 5.2.1 on 2025-06-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('collection', models.IntegerField()),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieApp.movies')),
            ],
        ),
        migrations.CreateModel(
            name='OtherLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_language', models.CharField(max_length=100)),
                ('movie', models.ManyToManyField(blank=True, to='movieApp.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieApp.movies')),
            ],
        ),
    ]
