# Generated by Django 5.2.1 on 2025-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
