# Generated by Django 5.2.1 on 2025-06-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_moviedetails_otherlanguages_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='otherlanguages',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='production',
            name='movie',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieApp.moviedetails'),
        ),
        migrations.AddField(
            model_name='movies',
            name='other_languages',
            field=models.ManyToManyField(blank=True, to='movieApp.otherlanguages'),
        ),
        migrations.AddField(
            model_name='movies',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieApp.production'),
        ),
    ]
