# Generated by Django 5.2.1 on 2025-06-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_remove_moviedetails_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='budget',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='collection',
            field=models.CharField(),
        ),
    ]
