# Generated by Django 5.2.1 on 2025-08-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0009_remove_user_age_user_display_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
