# Generated by Django 5.2.1 on 2025-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0010_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
