# Generated by Django 5.2.1 on 2025-08-05 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0011_movies_is_premium_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
